# EJERCICIO 9.1
Escriba en forma matricial el conjunto siguiente de ecuaciones:
50 = 5x
3 + 2x2
10 –  x
1 = x3
3x
2 + 8x1 = 20
b)  Escriba la transpuesta de la matriz de coeficientes

In [8]:
import numpy as np
#from openmat import *

print "\nSistema de Ecuaciones:"
print "50 = 5X3 + 2X2"
print "10-X1 = X3"
print "3X2 + 8X1 = 20"

print "\na) Forma Matricial Coeficientes (Matriz Aumentada):"
M = np.array([[0, 2, 5, 50], [-1, 0, -1, -10], [8, 0, 3, 20]])

def transpuesta(matriz):
        rows = len(matriz)
        cols = len(matriz[0])
        return [[matriz[j][i] for j in xrange(rows)] for i in xrange(cols)]
     
print "Original"
print_r(M)
print "\nb) Transpuesta Matriz Coeficientes"
print "TRANSPUESTA"
print_r(transpuesta(M))



Sistema de Ecuaciones:
50 = 5X3 + 2X2
10-X1 = X3
3X2 + 8X1 = 20

a) Forma Matricial Coeficientes (Matriz Aumentada):
Original
[ 0  2  5 50]
[ -1   0  -1 -10]
[ 8  0  3 20]

b) Transpuesta Matriz Coeficientes
TRANSPUESTA
[0, -1, 8]
[2, 0, 0]
[5, -1, 3]
[50, -10, 20]


# EJERCICIO 9.2
Ciertas matrice están definidas como sigue:
[A]=|4 7|       [B]=|4 3 7|   [C]=|3|    [D]=|9 4 3 -6|    [E]=|1 5 8|    [F]=|3 0 1|       [G]=|7 6 4|
    |1 2|           |1 2 7|       |6|        |2 -1 7 5|        |7 2 3|        |1 7 3|
    |5 6|           |1 0 4|       |1|                          |4 0 6|
a)  ¿Cuáles son las dimensiones de las matrices?
b)  Identifique las matrices cuadrada, columna y renglón.
c)  ¿Cuáles son los valores de los elementos  a12,  b23,  d32,  e22, 
f12 y  g12?
d)  Ejecute las operaciones siguientes:
1) [E] + [B]  7) [B]  × [A]
2) [A] + [F]  8) [D] T
3) [B] – [E]  9) [A]  × { C}
4) 7  × [B] 10) [I] × [B]
5) [E]  × [B] 11) [E] T [E]
6) { C} T 12) { C} T { C}

In [6]:
import numpy as np

def comparar_tam(Mat1,Mat2):
    if Mat1.shape == Mat2.shape:
        return True
    else:
        return False
        
        
def suma(Mat1,Mat2):
    if comparar_tam(Mat1,Mat2):
        m,n = Mat1.shape   # dimensiones de la matriz
        T = np.zeros((m,n)) #Creamos una matriz ceros temporal
        for i in range(0,m):
            for j in range(0,n):
                T[i,j] = Mat1[i,j] + Mat2[i,j]
        return T #resultado
    else:
        return None
    
def diferencia( Mat1, Mat2):
    if comparar_tam(Mat1,Mat2):
        m,n = Mat1.shape   #dimensiones de la matriz
        T = np.zeros((m,n))   #Creamos una matriz ceros Temporal
        for i in range(0,m):
            for j in range(0,n):
                T[i,j] = Mat1[i,j] - Mat2[i,j]
                return T  #resultado
    else:
        return None
    
    
def producto_escalar(c,Mat):
    m, n = Mat.shape     #dimensiones de la matriz
    T = np.zeros((m,n))  #Creamos una matriz de ceros temporal
    for i in range(0, m):
        for j in range(0, n):
            T[i,j] = Mat[i,j] * c    #Se multiplica por el escalar 
    return T

def producto(Mat1,Mat2):
    m1, n1 = Mat1.shape#Obtenemos dimensiones Matriz1
    m2, n2 = Mat2.shape#Obtenemos dimensiones Matriz2
    if n1 == m2:
        T = np.zeros((m1,n2))
        r = n1
        for i in range(0, m1):
            for j in range(0, n2):
                suma = 0#Guarda temporalmente la suma de los productos fila x columna
                for k in range(0, r):
                    suma += Mat1[i,k] * Mat2[k,j]
                T[i,j] = suma# Asignamos el valor de los productos
            return T   # resultado
    else:
        return None  #  no es posible realizar producto

def tr(Mat):
    m, n = Mat.shape  #Obtengo el tamanio de la matriz
    if m == n:#Verifica que la matriz sea cuadrada
        traza = 0
        for i in range(0, m):
            traza += Mat[i,i]		#Obtiene la traza de la matriz
        return traza
    else:
        return None

# Define la transpuesta de una matriz, return->Mat
# param:(Mat:Matriz)

def transpuesta(Mat):
    m, n = Mat.shape#Obtenemos el tamanio de la matriz m x n
    Mat_T = np.zeros((n, m))#Creamos la matriz transpuesta de zeros de tamanio n x m
    for i in range(0, m):
        for j in range(0, n):
            Mat_T[j,i] = Mat[i,j]
    return Mat_T #Retornamos el resultado

A = np.array([[4,7],[1,2],[5,6]])
B = np.array([[4,3,7],[1,2,7],[1,0,4]])
C = np.array([[3],[6],[1]])
D = np.array([[9,4,3,-6],[2,-1,7,5]])
E = np.array([[1,5,8],[7,2,3],[4,0,6]])
F = np.array([[3,0,1],[1,7,3]])
G = np.array([[7,6,4]])
#punto a
print "Dimensiones de las matrices\n"
print "-Matriz A: ", A.shape[0], " x ", A.shape[1]
print A
print "\n-Matriz B: ", B.shape[0], " x ", B.shape[1]
print B
print "\n-Matriz C: ", C.shape[0], " x ", C.shape[1]
print C
print "\n-Matriz D: ", D.shape[0], " x ", D.shape[1]
print D
print "\n-Matriz E: ", E.shape[0], " x ", E.shape[1]
print E
print "\n-Matriz F: ", F.shape[0], " x ", F.shape[1]
print F
print "\n-Matriz G: ", G.shape[0], " x ", G.shape[1] 
print G
print "FIN PUNTO a)"
# Punto b) 
print "Matrizes Cuadradas, columna y renglon"
print "Matriz CUADRADA:"
print "Matriz B:"
print B
print "\nMatriz E:"
print E
print "\nMatriz COLUMNA:"
print "Matriz C:"
print C
print "\nMatriz RENGLÓN:"
print "Matriz G:"
print G
print "FIN PUNTO b)\n"
#punto c)
print "¿Cuáles son los valores de los elementos  a12,  b23,  d32,  e22,f12 y  g12?"
print "-Matriz A:"
print A
print "Elemento a12= ", A[1-1,2-1]
print "\n-Matriz B:"
print B
print "Elemento b23= ", B[2-1,3-1]
print "\n-Matriz D:"
print D
print "Elemento d32= No Existe. Sobrepasa limites de la matriz." 
print "\n-Matriz E:"
print E
print "Elemento e22= ", E[2-1,2-1]
print "\n-Matriz F:"
print F
print "Elemento f12= ", F[1-1,2-1]
print "\n-Matriz G:"
print G
print "Elemento g12= ", G[1-1,2-1]
print "FIN PUNTO c)\n"
print "d) Realizar las siguientes operaciones:\n"
print "1.|E|+|B|\n"
T1=suma(E,B)
print T1
print "\n2.|A|+|F|\n"
T2=suma(A,F)
print T2
print "\n3.|B|-|E|\n"
T3=diferencia(B,E)
print "\n4.7 x |B|\n"
T4=producto_escalar(7,B)
print T4
print "\n5.|E| x |B|\n"
T5=producto(E,B)
print T5
print "\n6.tras|C|\n"
T6=transpuesta(C)
print T6
print "\n7.|B| x |A|\n"
T7=producto(B,A)
print T7
print "\n8.tras|D|\n"
T8=transpuesta(D)
print T8
print "\n9.|A| x |C|\n"
T9=producto(A,C)
print T9
print "\n10.|I| x |B|\n"
"T10=producto(I,B)"
print "I NO EXISTE"
print "\n11.tras|E| x |E|\n"
T7=transpuesta(E)
T11=producto(T7,E)
print T11
print "\n12.tras|C| x |C|\n"
T7=transpuesta(C)
T12=producto(T7,C)
print T12






Dimensiones de las matrices

-Matriz A:  3  x  2
[[4 7]
 [1 2]
 [5 6]]

-Matriz B:  3  x  3
[[4 3 7]
 [1 2 7]
 [1 0 4]]

-Matriz C:  3  x  1
[[3]
 [6]
 [1]]

-Matriz D:  2  x  4
[[ 9  4  3 -6]
 [ 2 -1  7  5]]

-Matriz E:  3  x  3
[[1 5 8]
 [7 2 3]
 [4 0 6]]

-Matriz F:  2  x  3
[[3 0 1]
 [1 7 3]]

-Matriz G:  1  x  3
[[7 6 4]]
FIN PUNTO a)
Matrizes Cuadradas, columna y renglon
Matriz CUADRADA:
Matriz B:
[[4 3 7]
 [1 2 7]
 [1 0 4]]

Matriz E:
[[1 5 8]
 [7 2 3]
 [4 0 6]]

Matriz COLUMNA:
Matriz C:
[[3]
 [6]
 [1]]

Matriz RENGLÓN:
Matriz G:
[[7 6 4]]
FIN PUNTO b)

¿Cuáles son los valores de los elementos  a12,  b23,  d32,  e22,f12 y  g12?
-Matriz A:
[[4 7]
 [1 2]
 [5 6]]
Elemento a12=  7

-Matriz B:
[[4 3 7]
 [1 2 7]
 [1 0 4]]
Elemento b23=  7

-Matriz D:
[[ 9  4  3 -6]
 [ 2 -1  7  5]]
Elemento d32= No Existe. Sobrepasa limites de la matriz.

-Matriz E:
[[1 5 8]
 [7 2 3]
 [4 0 6]]
Elemento e22=  2

-Matriz F:
[[3 0 1]
 [1 7 3]]
Elemento f12=  0

-Matriz G:
[[7 6 4]]
Elemento g12=  6
FIN P

# EJERCICIO 9.3